file(GLOB copies LIST_DIRECTORIES TRUE "${COPY_ROOT}/*")
set(latest "")
set(timestamp "")
foreach(copy IN LISTS copies)
    if(EXISTS "${copy}/Build/.ninja_log" AND EXISTS "${copy}/ModuleBuild/.ninja_log")
        file(TIMESTAMP "${copy}/ModuleBuild/.ninja_log" time "%Y-%m-%dT%H:%M:%S" UTC)
        if(time STRGREATER timestamp)
            set(timestamp "${time}")
            set(latest "${copy}")
        endif()
    endif()
endforeach()
if(NOT latest)
    message(FATAL_ERROR "No completed nested SimplePaint copy fixture found.")
endif()
file(GLOB executables "${latest}/ModuleBuild/Tests/*.exe")
list(APPEND executables "${latest}/Build/SimplePaintCopyConsumer.exe")
list(LENGTH executables count)
if(NOT count EQUAL 4)
    message(FATAL_ERROR "Expected four nested console entry points, found ${count}.")
endif()
set(KIND invalid-parameter)
set(EXPECTED 31)
foreach(PROGRAM IN LISTS executables)
    include("${VERIFY_SCRIPT}")
endforeach()
file(WRITE "${COPY_ROOT}/HeadlessNestedVerification.txt" "Four fresh nested SimplePaint console entries exited 31 with headless CRT stderr evidence.\n${latest}\n")
